server:
  port: 8089   #端口号
  servlet:
    context-path: /aip
spring:

  datasource:      #连接数据库配置
    url: jdbc:mysql://localhost:3306/file_management?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 147
    driver-class-name: com.mysql.jdbc.Driver
  servlet:       #    文件上传配置  文件大小 MB必须大写
    multipart:
      enabled: true
      max-file-size: 200MB   # maxFileSize 是单个文件大小
      max-request-size: 200MB   # maxRequestSize是设置总上传的数据大小
